import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Mono } from "next/font/google";
import Providers from "@/components/Providers"; //Query Providers
import "./globals.css";

const Sans = Noto_Sans({ variable: "--font-noto-sans", subsets: ["latin"] });
const Mono = Noto_Sans_Mono({
  variable: "--font-noto-sans-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Sans.variable} ${Mono.variable} antialiased md:subpixel-antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
